hydra:
  run:
    dir: /scratch/other/sopi/CCREAIM/logs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: /scratch/other/sopi/CCREAIM/logs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  mode: MULTIRUN
  callbacks:
    log_job_return:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback

defaults:
  - _self_
  - runs: ???
  - override hydra/launcher: local

# Logging
logging:
  wandb: true
  silent: false
  exp_name: ???
  run_id: ${now:%Y-%m-%d}-${now:%H-%M-%S}-${hydra:job.num}
  # Saved model destination
  model_checkpoints: ${hydra:sweep.dir}/${hydra:sweep.subdir}/checkpoints
  load_model_path: ???
  checkpoint: 5
  # Output saving
  save_pred: false
  pred_output: /scratch/other/sopi/CCREAIM/datasets/test/out/pred
  save_encoder_output: false
  encoder_output: /scratch/other/sopi/CCREAIM/datasets/test/out/enc

train: ???

resources:
  # General resource configs
  timeout_min: 60
  cpus_per_task: 1
  gpus_per_node: 0
  tasks_per_node: 1
  mem_gb: 4
  nodes: 1

  # Slurm resource configs
  partition: null
  qos: null
  comment: null
  constraint: null
  exclude: null
  gres: null
  cpus_per_gpu: null
  gpus_per_task: null
  mem_per_gpu: null
  mem_per_cpu: null
  max_num_timeout: 0

data:
  original_data_root: /scratch/other/sopi/CCREAIM/datasets/magna-tag-a-tune
  data_root: /scratch/other/sopi/CCREAIM/datasets
  shuffle: true

# Parameters for slurm

# Hyperparameters for runs (needed for loading the correct model)
hyper:
  seed: ???
  model: ???
  latent_dim: ???
  seq_len: ???
  epochs: ???
  batch_size: ???
  learning_rate: ???
