hydra:
  run:
    dir: /scratch/other/sopi/CCREAIM/logs/hydra_output/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: /scratch/other/sopi/CCREAIM/logs/hydra_output/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  mode: MULTIRUN

defaults:
  - _self_
  - runs: ???
  - override hydra/launcher: ext_submitit_local

# Logging
logging:
  save_logging: true
  save_model: true
  wandb: true
  silent: false
  exp_name: base
  run_suffix: 0
  # Saved model destination
  model_root: /scratch/other/sopi/CCREAIM/trained_models
  checkpoint: 0
  # Output saving
  save_pred: false
  pred_output: /scratch/other/sopi/CCREAIM/datasets/test/out/pred
  save_encoder_output: false
  encoder_output: /scratch/other/sopi/CCREAIM/datasets/test/out/enc

train: ???

data:
  original_data_root: /scratch/other/sopi/CCREAIM/datasets/magna-tag-a-tune
  data_root: /scratch/other/sopi/CCREAIM/datasets
  shuffle: true

# Parameters for slurm

# Hyperparameters for runs (needed for loading the correct model)
hyper:
  seed: ???
  model: ???
  seq_len: ???
  epochs: ???
  batch_size: ???
  learning_rate: ???
