hydra:
  run:
    dir: /scratch/other/sopi/CCREAIM/logs/hydra_output/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

defaults:
    - base.yaml
    - _self_
    - runs: smoke_test
    #- override hydra/launcher: submitit_slurm


# Parameters for slurm
gres: gpu:v100:1

# Saved model destination
model_path: /scratch/other/sopi/CCREAIM/trained_models
checkpoint: 0

# Data
save_pred: false
pred_output: /scratch/other/sopi/CCREAIM/datasets/test/out/pred
save_encoder_output: false
encoder_output: /scratch/other/sopi/CCREAIM/datasets/test/out/enc


# Hyperparameters for training
model: ae
seq_length: 1000
epochs: 10
batch_size: 8
learning_rate: 1e-3
shuffle: true
