hydra:
  run:
    dir: /scratch/other/sopi/CCREAIM/logs/hydra_output/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

defaults:
    - _self_
    - runs: smoke_test
    #- override hydra/launcher: submitit_slurm

# Logging
save_logging: true
save_model: true
wandb: true
silent: false
seed: 0
exp_name: base
run_id: 0
run_suffix: 0


# Parameters for slurm
gres: gpu:v100:1

# Saved model destination
model_path: /scratch/other/sopi/CCREAIM/trained_models
checkpoint: 0

# Data
#original_data_root: /scratch/other/sopi/CCREAIM/datasets/magna-tag-a-tune
#data_root: /scratch/other/sopi/CCREAIM/datasets

original_data_root: /scratch/other/sopi/CCREAIM/datasets/test/in
data_root: /scratch/other/sopi/CCREAIM/datasets/test/out


# Hyperparameters for training
model: ae
seq_length: 1000
epochs: 10
batch_size: 8
learning_rate: 1e-3
shuffle: true
