hydra:
  run:
    dir: /scratch/other/sopi/CCREAIM/logs/hydra_output/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

defaults:
    - base.yaml
    - _self_
    - runs: smoke_test
    #- override hydra/launcher: submitit_slurm

train: true

# Parameters for slurm
gres: gpu:v100:1

# Saved model destination
checkpoint: 0

# Hyperparameters for training
model: ae
seq_length: 1000
epochs: 10
batch_size: 8
learning_rate: 1e-3
shuffle: true
