# @package _global_
process:
  train: true
  cross_val_k: 0

logging:
  exp_name: smoke

data:
  data_tar: /scratch/other/sopi/CCREAIM/datasets/test/out/chopped_65536.tar

hyper:
  model: ae
  seed: 0
  latent_dim: 16
  seq_len: 65536
  epochs: 2
  batch_size: 8
  learning_rate: 1e-4
