# @package _global_
process:
  train: true
  cross_val_k: 0

logging:
  exp_name: system
  checkpoint: 2

hyper:
  model: ae
  seed: 0
  latent_dim: null #1,2,4,8
  seq_len: 65536
  epochs: 10
  batch_size: 32
  learning_rate: 1e-4

resources:
  # General resource configs
  timeout_min: 1000
  cpus_per_task: null
  gpus_per_node: null
  tasks_per_node: 1
  mem_gb: 8
  nodes: 1

  # Slurm resource configs
  gres: null
  cpus_per_gpu: 2
  gpus_per_task: 1
  mem_per_gpu: null
  mem_per_cpu: null
  max_num_timeout: 0
