# @package _global_
process:
  train: true
  cross_val_k: 1

logging:
  exp_name: system
  checkpoint: 10
  save_pred: true

data:
  data_tar: /scratch/other/sopi/CCREAIM/datasets/chopped_65536.tar

hyper:
  model: e2e-chunked
  seed: 0
  latent_dim: 32
  num_seq: 16
  seq_cat: true
  seq_len: 4096
  epochs: 50
  batch_size: 64
  learning_rate: 1e-6
  spectral_loss:
    weight: 1e-3
    stft_bins:
      - 2048
      - 1024
      - 512
    stft_hop_length:
      - 240
      - 120
      - 50
    stft_window_size:
      - 1200
      - 600
      - 240

resources:
  # DataLoader num_workers parameter
  num_workers: 4

  # General resource configs
  timeout_min: 720
  cpus_per_task: 4
  gpus_per_node: 1
  tasks_per_node: 1
  mem_gb: 12
  nodes: 1
