# @package _global_
process:
  train: true
  cross_val_k: 1

logging:
  exp_name: smoke
  save_pred: true
  save_one_per_batch: false

data:
  data_tar: /scratch/other/sopi/CCREAIM/datasets/test/out/chopped_65536.tar

hyper:
  model: res-vae
  seed: 0
  latent_dim: 16
  seq_len: 65536
  epochs: 50
  batch_size: 8
  learning_rate: 1e-4
  kld_loss:
    weight: 1e-3
  spectral_loss:
    weight: 1e-2
    stft_bins:
      - 2048
      - 1024
      - 512
    stft_hop_length:
      - 240
      - 120
      - 50
    stft_window_size:
      - 1200
      - 600
      - 240
  res_ae:
    levels: 1 # orig 3
    downs_t: # orig [3,2,2]
      - 3
    strides_t: # orig [2,2,2]
      - 4
    input_emb_width: 1
    block_width: 32
    block_depth: 2
    block_m_conv: 1.0
    block_dilation_growth_rate: 3
    block_dilation_cycle: null


resources:
  # DataLoader num_workers parameter
  num_workers: 2

  # General resource configs
  timeout_min: 120
  cpus_per_task: 2
  gpus_per_node: 0
  tasks_per_node: 1
  mem_gb: 16
  nodes: 1
