# @package _global_
train: true

logging:
  exp_name: system

data:
  data_root: /scratch/other/sopi/CCREAIM/datasets/magna-tag-a-tune_enc_lr1e-4

hyper:
  model: transformer
  seq_len: 65536
  seed: 0
  latent_dim: 16
  epochs: 100
  batch_size: 8
  learning_rate: 1e-3
