# @package _global_
train: true

logging:
  exp_name: system

hyper:
  model: ae
  seed: 0
  latent_dim: 16
  seq_len: 65536
  epochs: 100
  batch_size: 8
  learning_rate: 1e-4
  spectral_loss:
    weight: 1e-2
    stft_bins:
      - 2048
      - 1024
      - 512
    stft_hop_length:
      - 240
      - 120
      - 50
    stft_window_size:
      - 1200
      - 600
      - 240
