# @package _global_
process:
  train: true
  cross_val_k: 1

logging:
  exp_name: smoke
  save_pred: true
  save_one_per_batch: false
  save_encoder_output: true
  save_transformer_training_data: true
  transformer_training_data_tar_orig: /scratch/other/sopi/CCREAIM/datasets/test/out/chopped_65536.tar
  transformer_training_data_tar_out: ${hydra:sweep.dir}/${hydra:sweep.subdir}/
  transformer_training_num_seq: 16

data:
  data_tar: /scratch/other/sopi/CCREAIM/datasets/test/out/chopped_4096.tar

hyper:
  model: res-vqvae
  seed: 0
  latent_dim: 64 #1,2,4,8
  seq_len: 4096
  epochs: 1
  batch_size: 10
  learning_rate: 1e-5
  spectral_loss:
    weight: 1e-5
    stft_bins:
      - 2048
      - 1024
      - 512
    stft_hop_length:
      - 240
      - 120
      - 50
    stft_window_size:
      - 1200
      - 600
      - 240
  res_ae:
    levels: 1 # orig 3
    downs_t: # orig [3,2,2]
      - 5
    strides_t: # orig [2,2,2]
      - 2
    input_emb_width: 1
    block_width: 32
    block_depth: 3
    block_m_conv: 1.0
    block_dilation_growth_rate: 3
    block_dilation_cycle: null
  vqvae:
    num_embeddings: 512
    beta: 0.02
    reset_patience: 1.25
