# @package _global_

train: false

data:
  model_path: /scratch/other/sopi/CCREAIM/trained_models/test
  original_data_root: /scratch/other/sopi/CCREAIM/datasets/magna-tag-a-tune
  data_root: /scratch/other/sopi/CCREAIM/datasets/

hyper:
  model: ae
  seed: 0
  seq_len: 65536
  epochs: 100
  batch_size: 8
  learning_rate: 1e-4

logging:
  exp_name: system-test
  load_model_path: /scratch/other/sopi/CCREAIM/logs/multirun/2022-11-03/16-20-39/0/checkpoints/ae_seqlen-65536_bs-8_lr-0.0001_seed-0_ep-005.pth
  # Data
  save_pred: false
  save_encoder_output: true
  encoder_output: /scratch/other/sopi/CCREAIM/datasets/magna-tag-a-tune_enc_lr1e-4
